labextension:
  # ----------------------------------------------------------------------------
  # Dask Labextension Configuration
  # ----------------------------------------------------------------------------
  
  # Factory: How to create clusters from Labextension
  # This prevents LocalCluster from being used
  factory:
    module: "coffea_casa"
    class: "CoffeaCasaCluster"
    args: []
    kwargs: {}
  
  # Default settings when creating new cluster
  default:
    workers: null
    adapt:
      minimum: 1
      maximum: 50
      interval: "2s"
      wait_count: 3

  initial: []  # Don't auto-start clusters!
