# Create release only
name: Openscience Harbor Registry CD - Hub Image

on:
  push:
    paths:
      - 'charts/coffea-casa/docker/**'
    branches:
      - master

env:
  GITHUB_SHA: ${{ github.sha }}
  GITHUB_REF: ${{ github.ref }}

jobs:
  matrix-build:
    strategy:
      fail-fast: false
      matrix:
        IMAGE: ["k8s-hub-coffea-casa"]
    name: ${{ matrix.IMAGE }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Set Job Environment Variables
        run: |
          TAG="${GITHUB_REF##*/}"
          echo "TAG=${TAG}" >> $GITHUB_ENV
      - name: Login to Openscience Harbor Registry
        uses: docker/login-action@v1
        with:
          registry: hub.opensciencegrid.org
          username: ${{ secrets.HARBOR_USER }}
          password: ${{ secrets.HARBOR_PASSWORD }}
      - name: Build Container Image
        run: |
          cd charts/coffea-casa/docker/${{ matrix.IMAGE }}
          docker build -t hub.opensciencegrid.org/coffea-casa/${{ matrix.IMAGE }}:development .
      - name: Push to Openscience Harbor Registry
        run: |
          docker push hub.opensciencegrid.org/coffea-casa/${{ matrix.IMAGE }}:development