# Create release only
name: Openscience Harbor Registry Publish

on:
  release:
    types: [created]

env:
  GITHUB_SHA: ${{ github.sha }}
  GITHUB_REF: ${{ github.ref }}


jobs:
  matrix-build:
    strategy:
      fail-fast: false
      matrix:
        IMAGE: [coffea-casa,
                coffea-casa-analysis,
                coffea-casa-cc7,
                coffea-casa-analysis-cc7]
    name: ${{ matrix.IMAGE }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Set Job Environment Variables
        run: |
          TAG="${GITHUB_REF##*/}"
          echo "TAG=${TAG}" >> $GITHUB_ENV
      - name: Login to Openscience Harbor Registry
        uses: docker/login-action@v1
        with:
          registry: hub.opensciencegrid.org
          username: ${{ secrets.HARBOR_USER }}
          password: ${{ secrets.HARBOR_PASSWORD }}
      - name: Build Container Image
        run: |
          cd docker/${{ matrix.IMAGE }}
          docker build -t hub.opensciencegrid.org/coffea-casa/${{ matrix.IMAGE }}:latest -t hub.opensciencegrid.org/coffea-casa/${{ matrix.IMAGE }}:$TAG .
      - name: Push to Openscience Harbor Registry
        run: |
          docker push hub.opensciencegrid.org/coffea-casa/${{ matrix.IMAGE }}:latest
          docker push hub.opensciencegrid.org/coffea-casa/${{ matrix.IMAGE }}:$TAG