# Create release only
name: Openscience Harbor Registry CD - Coffea-casa

on:
  push:
    paths:
      - './docker/prepare-env/prepare-env-cc.sh'
      - './docker/dask/*'
      - './docker/uproot/*'
      - './docker/Dockerfile.cc-centos7'
      - './docker/Dockerfile.cc-ubuntu'
    branches:
      - master

env:
  GITHUB_SHA: ${{ github.sha }}
  GITHUB_REF: ${{ github.ref }}

jobs:
  matrix-build:
    strategy:
      fail-fast: false
      matrix:
         IMAGE: [cc-centos7,
                cc-ubuntu
                ]
    name: ${{ matrix.IMAGE }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Set Job Environment Variables
        run: |
          TAG="${GITHUB_REF##*/}"
          echo "TAG=${TAG}" >> $GITHUB_ENV
      - name: Login to Openscience Harbor Registry
        uses: docker/login-action@v1
        with:
          registry: hub.opensciencegrid.org
          username: ${{ secrets.HARBOR_USER }}
          password: ${{ secrets.HARBOR_PASSWORD }}
      - name: Build Container Image
        run: |
          cd docker
          docker build --build-arg TAG="development" -t hub.opensciencegrid.org/coffea-casa/${{ matrix.IMAGE }}:development  -f Dockerfile.${{ matrix.IMAGE }} .
      - name: Push to Openscience Harbor Registry
        run: |
          docker push hub.opensciencegrid.org/coffea-casa/${{ matrix.IMAGE }}:development